"""Escalation thresholds and alert taxonomy for CCTV incident handling."""

STAGE_1_DELAY_MINUTES = 0
STAGE_2_DELAY_MINUTES = 15
STAGE_3_DELAY_MINUTES = 30
STAGE_4_DELAY_MINUTES = 60

CAMERA_FAILURE = "CAMERA_FAILURE"
STREAM_FAILURE = "STREAM_FAILURE"
SWITCH_FAILURE = "SWITCH_FAILURE"
PREDICTED_FAILURE = "PREDICTED_FAILURE"
ALERT_TYPES = {CAMERA_FAILURE, STREAM_FAILURE, SWITCH_FAILURE, PREDICTED_FAILURE}

ESCALATION_RISK_LEVELS = {"HIGH", "CRITICAL"}
